# Generated by Django 6.1.1 on 2026-09-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=64)),
                ('at', models.DateTimeField()),
                ('referrer', models.CharField(blank=True, max_length=2000)),
                ('user_agent', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'code', 'at'], name='links_click_tenant__1da60f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=64)),
                ('target_url', models.URLField(max_length=2000)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'code'), name='unique_tenant_code')],
            },
        ),
    ]
